version: "3"
services:
  minecraft:
    tty: true
    build:
      context: ./
      dockerfile:  ./Dockerfile
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - ./server:/opt/minecraft
    env_file:
      - ./.env
